### ISSUE TITLE
bug: grub.cfg file issue with Fedora >33 workstation

### ISSUE THREAD

**Issue by OneRandom1509** [sandesh236/sleek--themes#19]
As specified [in the fedora docs](https://fedoraproject.org/wiki/GRUB_2#Updating_the_GRUB_configuration_file), the file `/boot/efi/EFI/fedora/grub.cfg` should not be touched in versions of fedora greater than 33.

In the newer version it's better to use `grub2-mkconfig -o /boot/grub2/grub.cfg`

I have forked the repo and tried the new changes it on my fedora 39 workstation and it works fine, I can make the PR for further review.

**Comment by sandesh236** [comment]
Has been fixed.
