### ISSUE TITLE
Increase Title Size

### ISSUE THREAD

**Issue by mrfoxie** [sandesh236/sleek--themes#3]
I like your concept and I loved it, but I was thinking to increase the font size of the title
```title-text:""
message-font: "DejaVu Sans Regular 14"
message-color: "#FFFFFF"
terminal-font: "Terminus Regular 14"
terminal-box: "terminal_*.png"
```
but I couldn't found a way to change it.

**Comment by sandesh236** [comment]
By referring to title, Do you mean the title of the operating system. Above styling is for the terminal that you could access from bootloader by pressing 'c' key.  
`boot_menu
{
item_font: " change the font size of the item here but be sure you have the that specific font available. Put that specific font in the same folder"
}`

**Comment by mrfoxie** [comment]
```
title-text:" "
message-font: "DejaVu Sans Regular 14"
message-color: "#757575"
terminal-font: "Terminus Regular 14"
terminal-box: "terminal_*.png"
```
I'm talking about [Sleektheme-orange](https://github.com/sandesh236/sleek--themes/blob/master/Sleektheme-orange/sleek/theme.txt) the title text

**Comment by sandesh236** [comment]
`+label{
text="Grub Bootloader"
font = "DejaVu Sans Regular 48"
color="#4700E7"
left = 50%-200
top = 15%
height = 20
width = 400      
align = "center"

}`
to change the font size of Title (i am considering Grub bootloader and your name as title. when you select 'y' to use name in bootloader your name replace the Grub Bootloader label).  Change the font in above code.

**Comment by mrfoxie** [comment]
thank you pal
